# Generated by Django 3.2 on 2021-09-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_notes_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
