# Generated by Django 3.2 on 2021-09-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_notes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
